### ISSUE TITLE
Controlling the user initiating the invite

### ISSUE THREAD

**Issue by gilhoffer** [vestris/slack-invite#11]
Hey,
Great bot! I'm trying to use the service.

Is there a way to control **from** whom the invite will be sent? Mostly I wouldn't like the invites sent to state my personal email address (I have no problem adding another user to the workspace in order to accomplish this).

Thanks!
Gil

**Comment by dblock** [comment]
The invite is [sent](https://github.com/vestris/slack-invite/blob/c2e7ee516e1cdfe155a695d8631ecf5d31586d12/slack-invite/models/invitation.rb#L24) by the [admin user that installed the bot](https://github.com/vestris/slack-invite/blob/b7e5a9dc77ab94bf7b12a13348fb9895ddefedd9/slack-invite/models/user.rb#L93).

I see two options:

1) Create a new admin user, uninstall and (re)install the bot using that. 
2) We could implement a workflow to prompt a different user to become the sender, in which case they would have to click on a few buttons and authorize themselves with the bot (and thus updating the admin token).

No timeline promises on (2), but maybe you have developer hands and want a free license? :)

**Comment by gilhoffer** [comment]
Thanks Daniel for the very quick response!

For now I did the workaround you suggested in (1), worked like a charm.

I might look into (2), but can't promise anything either :)

**Comment by dblock** [comment]
Implemented in https://github.com/vestris/slack-invite/commit/80ef09fd981f4281aa6c8775fafae58077007356.
