### ISSUE TITLE
Better experience for already-registered users

### ISSUE THREAD

**Issue by accorvin** [vestris/slack-invite#35]
I'm hoping it is possible to improve the experience for users who are already signed up for the target Slack workspace.

# Use case
On our community website, I want to have a single button that a user can click to get to our Slack workspace. That button will link to our invite.playplay.io site where they can sign up.

This works wonderfully for users who are not already part of the slack workspace, but falls short for someone who is already part of the slack workspace and just wants to use the link to get there.

Some potential solutions I'm imagining:
1) A link on the invite.playplay.io pointing to our slack workspace. The page currently has the text `Get invited to team $WORKSPACE_NAME`. You could make `$WORKSPACE_NAME` a link to the actual workspace.

2) If you attempt to sign up and you've already done so, you will get an error message. You could update that error message to include a link to the slack workspace (something like `You are already a member of this slack workspace. Click here to get to it`

**Comment by dblock** [comment]
I think we should do both! Care to contribute?

**Comment by accorvin** [comment]
@dblock my ruby experience is _very_ rusty, so I can't promising anything. Scanning through the code, it's not obvious to me if there exists anywhere a pointer to the workspace URL. Do you know if the code captures that information anywhere?

If not, I'm thinking we'd need to add a configuration setting for the the administrator to provide that information via a call to the bot.

**Comment by dblock** [comment]
I'll help if you promise to hang in here with me :)

I would start by running this app locally, these [docs](https://github.com/vestris/slack-invite/blob/master/DEV.md) should be a decent start, but they might be old-ish. I can help when things don't work if you can't figure it out.

When the web page loads everything is keyed off `team_id`. If you look at the instance of a `Team` it has properties such as team `domain`, but if that's not enough, it has access to `team.slack_client` which is a client that uses the team's API key. You can call all slack web API methods including [`team_info`](https://api.slack.com/methods/team.info).

**Comment by accorvin** [comment]
@dblock I've been working through the [development instructions](https://github.com/vestris/slack-invite/blob/master/DEV.md) to get a local instance running to test. I've hit an issue that I'm hoping you can advise me on.

You specify [here](https://github.com/vestris/slack-invite/blob/master/DEV.md?plain=1#L27) to configure the Slack App's redirect URL to `http://localhost:5000`. It appears that Slack now requires that `https` be used. How are you getting around this? Do you somehow configure Unicorn to run with TLS locally?

**Comment by accorvin** [comment]
@dblock ignore the above question. I got it working with a local apache proxy and a self signed cert.

**Comment by accorvin** [comment]
@dblock I've managed to get this working. Expect a PR next week, just need to update the tests.

**Comment by dblock** [comment]
For more advanced features I use [ngrok](https://ngrok.com/), which gives me an external HTTPS URL. The only annoyance is for webhooks you have to change the URL every time you restart ngrok. Maybe I'll pay for it someday to get a stable URL :)

**Comment by dblock** [comment]
Link and icon added in https://github.com/vestris/slack-invite/commit/fff5ea00f122025d81c7eb6da0b848abb7cb5bf2. 

An error is displayed when a user is already invited in https://github.com/vestris/slack-invite/commit/7e94684c28e839798dfd0e7d82266298b197e5c3. 

An error is displayed if the user is already a member in https://github.com/vestris/slack-invite/commit/7e94684c28e839798dfd0e7d82266298b197e5c3.
